name: trending-topics

services:
  redis:
    image: 'redis:latest'
    restart: 'unless-stopped'
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: '10s'
    networks:
      - backend
  summary-cache:
    image: 'summary-cache:latest'
    restart: 'unless-stopped'
    depends_on:
      redis:
        condition: 'service_healthy'
    environment:
      REDIS_URL: 'redis://redis:6379'
    networks:
      - backend
    ports:
      - '8080:8080'

networks:
  backend: {}
